name: Terraform Deployment

on:
  issue_comment:
    types: [created]

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Check if the comment is on a pull request and contains /apply or /destroy
      - name: Check if PR comment contains /apply or /destroy
        if: github.event.issue.pull_request != null && (contains(github.event.comment.body, '/apply') || contains(github.event.comment.body, '/destroy'))
        run: |
          echo "PR comment contains /apply or /destroy, proceeding with the respective action."
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

         # Zip the file before running Terraform (optional step)
      - name: Zip a specific file
        run: |
          zip lambda_artifacts/lambda_function.zip lambda_artifacts/lambda_function.py

      # Configure AWS credentials (or any other provider)
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
          
      - name: Setup Terraform backend
        run: terraform init -backend-config="bucket=your-terraform-state-bucket" -backend-config="key=terraform.tfstate" -backend-config="region=${{ secrets.AWS_DEFAULT_REGION }}"

      # Plan Terraform Deployment
      - name: Terraform Plan
        run: terraform plan

     # Run Terraform Apply if the comment contains /apply
      - name: Terraform Apply
        run: terraform apply -auto-approve
        if: github.event.issue.pull_request != null && contains(github.event.comment.body, '/apply')

      # Run Terraform Destroy if the comment contains /destroy
      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        if: github.event.issue.pull_request != null && contains(github.event.comment.body, '/destroy')
      # Optional: Terraform Output
      - name: Terraform Output
        run: terraform output
